### PR TITLE
Add theme menu

### LINKED ISSUE #85: Feature Request: Reset theme toggle to auto
After toggling the theme button there is no way of setting it back to use the system default.

I imagine sth like, if the current theme is equal to the saved theme clicking the toggle again resets the theme back to system default by deleting the localStorage entry.

Not sure whether there should be a moon logo with (auto) attached whenever no theme is set or a user notification („Theme is now set by the system automatically“) when changed back to auto.

Pinging @Bellisario as I’ve seen, that you have thought about this issue already for Snapdrop

### PR DESCRIPTION
**Pull request by schlagmichdoch**
fixes #85

### CODE REVIEW

**Comment by fm-sys** [comment]
The new theme menu broke compatibility with "Snapdrop for Android". Hiding the menu again is easy, however it will cause an ugly UI if the user (accidentally) did change the theme:

grafik

I tried to switch back to 'auto' theme, however simulating a click to #theme-auto will just swap the theme. 

Possible solutions:
- Don't swap theme when clicking on 'auto'
- Provide an API / window event to change theme to 'auto' without explicit swapping

**Comment by schlagmichdoch** [comment]
Sorry @fm-sys ! I should probably always test compatibility with your app before deploying changes to the UI.. 

There are two possibilities to change the theme back to auto:
- clicking on `#theme-light`
- Executing `localStorage.removeItem('theme');`

I recommend to execute the second option every time the user changes the theme in your settings. This is the same for snapdrop.

Also, I will rename `#theme-wrapper` to `#theme` which will hide the toggle again on snapdrop-android

**Comment by schlagmichdoch** [comment]
You will need to reload the page after removing the localStorage entry.

Alternatively this is the method to remove any theme from the body:
https://github.com/schlagmichdoch/PairDrop/blob/master/public/scripts/theme.js#L62

**Comment by schlagmichdoch** [comment]
True, but I rather meant this is the way how the theme is set to auto.

In particular you need this:
```javascript
    document.body.classList.remove('dark-theme');
    document.body.classList.remove('light-theme');
```
But I don't understand why removing the localStorage setting and reloading is not sufficient. Do you have a working branch I can have a look at?

**Comment by fm-sys** [comment]
OK, I tried it again with `localStorage.removeItem('theme');`

Indeed, the icon does change after a refresh, however the theme doesn't align with the app theme.

grafik
grafik

I left out explicit reloading intentionally. Closing and reopening should have the same effect, and reloading would just increase startup time.

Branch:
https://github.com/fm-sys/snapdrop-android/tree/theme

**Pull request merged**
