### PR TITLE
Add Healthcheck to Dockerfile

### PR DESCRIPTION
**Pull request by kgncloud**
Hi there,

We would like to add a healthcheck to your amazing fork to further improve your image.

### CODE REVIEW

**Comment by schlagmichdoch** [comment]
Hi there,
Thanks for the PR! 
What exactly does this health check do? As I understand it, it checks whether localhost:3000 is available with wget every 30s. What happens if it is not available? What happens if this is run together with `—restart=always`? Should this be optional or is this a common way to do that? Do we need to add docs for this?

**Comment by kgncloud** [comment]
The healthcheck would as you said do the following:
- Give the Container 5 sec to start properly
- Try out every 30sec if the container is properly working by checking if the webserver is available if not mark the container as unhealthy
- The Unhealthy Status will be given when the healthcheck fails 3 times in a row
- The Command does not directly interfere with --restart=always since it is more build to start the container on a host boot and btw docker itself is lazy to read healthy and unhealthy status in standalone mode.
- To test the behavior in case of container failure it is recommended to use deunhealth as a helper
- The primary goal is to make it able to monitor if the service is down, this is especially good for docker swarm where we launched it

Here an attempt for documentation if wanted/needed:

This Dockerfile line is defining a HEALTHCHECK instruction, which specifies how Docker should check the health of the container. The HEALTHCHECK instruction is used to determine whether the container is working properly and ready to receive traffic.

The HEALTHCHECK command consists of several options:

--interval=30s: This option specifies the time interval at which the health check should be performed. In this case, the health check will be performed every 30 seconds.

--timeout=10s: This option specifies the amount of time to wait for a response from the health check command. If the response does not arrive within 10 seconds, the health check will be considered a failure.

--start-period=5s: This option specifies the amount of time to wait before starting the health check process. In this case, the health check process will begin 5 seconds after the container is started.

--retries=3: This option specifies the number of times Docker should retry the health check before considering the container to be unhealthy.

The CMD instruction is used to define the command that will be run as part of the health check. In this case, the command is "wget --quiet --tries=1 --spider http://localhost:3000/ || exit 1". This command will attempt to connect to http://localhost:3000/ and if it fails, it will exit with a status code of 1. If this command returns a status code other than 0, the health check will be considered a failure.

Overall, this HEALTHCHECK instruction is defining a health check process that will run every 30 seconds, wait up to 10 seconds for a response, begin 5 seconds after the container is started, and retry up to 3 times. The health check will consist of attempting to connect to http://localhost:3000/ and will consider the container to be unhealthy if it is unable to connect.

**Comment by schlagmichdoch** [comment]
Thanks for the thorough explanation!
So it's up to the user to define what should happen if the image is flagged as being unhealthy?

> Overall, this HEALTHCHECK instruction is defining a health check process that will run every 30 seconds, wait up to 10 seconds for a response, begin 5 seconds after the container is started, and retry up to 3 times. The health check will consist of attempting to connect to http://localhost:3000/ and will consider the container to be unhealthy if it is unable to connect.

I like that summary but I'm not sure where to put this documentation. Maybe at the end of [Docker Image self-built](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md#docker-image-self-built). With an additional sentence like: _See here how to use the HEALTHCHECK status of the docker file_ with _here_ linking to a guide for the HEALTHCHECK flag. Any suggestions?

**Comment by kgncloud** [comment]
The Possible Documentation is added to this PR. Recommended by CIS Docker Benchmark 1.4.0 is to directly include the Healthcheck into the Image if possible. :D

**Comment by schlagmichdoch** [comment]
Thanks for your contribution!

**Pull request merged**
