### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [PairDrop/pairdrop-spa](https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/).

Current translation status:

Weblate translation status

Todo:
- [x] Fix alert between upstream and Weblate: https://hosted.weblate.org/projects/pairdrop/pairdrop-spa/#alerts

### CODE REVIEW

**Comment by mickiemouse** [comment]
The Turkish translation done! Can you merge the Turkish language translation to project?

**Comment by schlagmichdoch** [comment]
Hey @mickiemouse,
Thanks for your contribution by translating to Turkish! I'm in the process of releasing version `v1.10.0` which will include the Turkish language and many more changes (see #209). Give me 1-2 more days and this will be live.

**Comment by mickiemouse** [comment]
Ok thank you so much.🥳

**Comment by schlagmichdoch** [comment]
@mickiemouse I have just merged and rebase all changes into this branch so everything is ready to be deployed. :tada:

As there have been quite a lot of changes please have a look at the [untranslated strings](https://hosted.weblate.org/translate/pairdrop/pairdrop-spa/tr/?q=state%3A<translated) and the [strings with failing checks](https://hosted.weblate.org/translate/pairdrop/pairdrop-spa/tr/?q=has:check). 

I will release the new version Tuesday evening but later changes will be quickly released as minor versions.

**Comment by mickiemouse** [comment]
Okey, thank you so much. I checked all [untranslated strings](https://hosted.weblate.org/translate/pairdrop/pairdrop-spa/tr/?q=state%3A%3Ctranslated) and the [strings with failing checks](https://hosted.weblate.org/translate/pairdrop/pairdrop-spa/tr/?q=has:check). I'm waiting forward to see!  🥳

**Comment by mickiemouse** [comment]
Hi. Some translated Turkish variables translations are changed and fixed. Can you add them to the project?
Thank you so much.
Best regards.

**Comment by schlagmichdoch** [comment]
This is tracked at #224. I will wait some days for more translation updates and release a new minor version then. Thanks for your contribution!

**Pull request closed without merging**
