### PR TITLE
feat(ghcr.io)  build container on tagged commits to ghcr.io

### PR DESCRIPTION
**Pull request by xstar97**
Hi. app looks really cool.

This workflow lets you create images for ghcr.io from tagged releases with a semVER version for example: `v0.0.1`.

### CODE REVIEW

**Comment by schlagmichdoch** [comment]
There won't be releases but tagged commits. Is this enough to trigger this action?

What does this action do exactly? It somehow uses github credentials. Where and when does this action run and with whose credentials?

**Comment by xstar97** [comment]
> There won't be releases but tagged commits. Is this enough to trigger this action?
> 
> What does this action do exactly? It somehow uses github credentials. Where and when does this action run and with whose credentials?

sorry for the late reply, it runs automatically with your own default credentials, you don't need to do anything other than just create tag either by release or tag commit.

a side note that you might get a write error to solve that:

head over to $yourOrganization → Packages → $yourPackage → Package settings (to the right / bottom)

And configure “Manage Actions access” section to allow the git repository in question write permissions on this package/docker repository

something like this: `https://github.com/users/schlagmichdoch/packages/container/pairdrop/settings`

**Comment by schlagmichdoch** [comment]
Great! Thanks for the explanation.
Would you suggest to add this to the [host-your-own.md documentation](https://github.com/schlagmichdoch/pairdrop/docs/host-your-own.md) ? How can I then pull this image?

**Comment by xstar97** [comment]
> Great! Thanks for the explanation. Would you suggest to add this to the [host-your-own.md documentation](https://github.com/schlagmichdoch/PairDrop/blob/master/docs/host-your-own.md) ? How can I then pull this image?

https://github.com/schlagmichdoch/PairDrop/pull/45

this is an example project of the same workflow in action:

https://github.com/xstar97/openvpn-client/pkgs/container/openvpn-client

```console
docker pull ghcr.io/xstar97/openvpn-client:v0.0.1
```

your pkg might be like this -> https://github.com/users/schlagmichdoch/packages/container/pairdrop

```console
docker pull ghcr.io/schlagmichdoch/pairdrop:latest
```

**Pull request merged**
