### PR TITLE
Better devicename

### PR DESCRIPTION
**Pull request by xundeenergie**
The devicename in the original layout is not good to see and sometimes hidden by status-messages... ("No server connection. Retry...")

grafik

That is the normal Layout.
grafik

I changed the position and fontsize (h1) of the devicename, so it looks like this:

grafik

It also works for smartphone-layout.

### CODE REVIEW

**Comment by schlagmichdoch** [comment]
I'll think about it but I would rather move the status notifications to the top to keep it tidy.

**Comment by xundeenergie** [comment]
Ok...
I like it, when the important information is good present :)
It preserves of mistakes.

**Comment by schlagmichdoch** [comment]
I will close this in favor of #57 

This also moves the user notifications to the top. Would be great if you could under https://pairdrop-dev.onrender.com/ and give feedback before I merge it :)

**Comment by xundeenergie** [comment]
> I will close this in favor of #57
> 
> This also moves the user notifications to the top. Would be great if you could under https://pairdrop-dev.onrender.com/ and give feedback before I merge it :)

I tried it... and i'm sorry... on my other phone, the username is hidden by the browsers address-bar... 

But it's not that big problem. My changes (i love to see essential informations easy and always) are small, an i will merge the masterbranch on updates into my own, local branch. ☺️

**Comment by schlagmichdoch** [comment]
> my other phone

Good to know! What kind of phone and browser is this?

**Comment by xundeenergie** [comment]
this is samsung A53 with Firefox and url-bar on bottom.

**Pull request closed without merging**
